<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Landscape.Tsi.Application\Landscape.Tsi.Application.csproj" />
    <ProjectReference Include="..\Landscape.Tsi.Infrastructure\Landscape.Tsi.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>landscape-tsi-web-development</UserSecretsId>
  </PropertyGroup>

</Project>
